package main

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

func (m *manager) configPath() string { return filepath.Join(m.root, "etc", "omd", "packages.conf") }

func (m *manager) settingsPath() string { return filepath.Join(m.root, "etc", "omd", "settings.conf") }

func (m *manager) loadConfig() (map[string]bool, error) {
	data, err := os.ReadFile(m.configPath())
	if err != nil {
		return nil, err
	}
	selected := make(map[string]bool)
	for i, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		id, state, ok := strings.Cut(line, "=")
		id, state = strings.TrimSpace(id), strings.TrimSpace(state)
		// Older configs may contain tools removed from the supported catalog.
		switch id {
		case "copilot-cli", "gemini-cli", "cursor-cli", "kimi-code":
			continue
		}
		known := slices.ContainsFunc(m.packages, func(p Package) bool {
			return p.ID == id
		})
		if !ok || !known || (state != "enabled" && state != "disabled") {
			return nil, fmt.Errorf("%s:%d: invalid package selection %q", m.configPath(), i+1, line)
		}
		selected[id] = state == "enabled"
	}
	return selected, nil
}

func atomicWrite(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	f, err := os.CreateTemp(filepath.Dir(path), ".omd-*")
	if err != nil {
		return err
	}
	defer os.Remove(f.Name())
	_, writeErr := io.WriteString(f, content)
	closeErr := f.Close()
	if err := errors.Join(writeErr, closeErr); err != nil {
		return err
	}
	return os.Rename(f.Name(), path)
}

func (m *manager) saveConfig(selected map[string]bool) error {
	var b strings.Builder
	b.WriteString("# Generated by omd\n")
	for _, p := range m.packages {
		state := "disabled"
		if selected[p.ID] {
			state = "enabled"
		}
		fmt.Fprintf(&b, "%s=%s\n", p.ID, state)
	}
	return atomicWrite(m.configPath(), b.String())
}

func (m *manager) generateEnv(selected map[string]bool) error {
	var b strings.Builder
	b.WriteString("# Generated by omd — do not edit\n# Regenerate with: omd env\n\ntypeset -U path\n")
	// Homebrew makes executables available; syntax highlighting wraps the other
	// plugins and widgets, so it must be loaded last.
	ordered := slices.Clone(m.packages)
	slices.SortStableFunc(ordered, func(a, b Package) int { return envPriority(a) - envPriority(b) })
	for _, p := range ordered {
		if selected[p.ID] && p.Env != "" && m.check(p.Check) {
			fmt.Fprintf(&b, "\n# %s\n%s", p.ID, p.Env)
		}
	}
	return atomicWrite(filepath.Join(m.root, "etc", "omd", "env.sh"), b.String())
}

func envPriority(p Package) int {
	if p.ID == "homebrew" {
		return -1
	}
	if p.ID == "zsh-syntax-highlighting" {
		return 1
	}
	return 0
}
