package main

import (
	"fmt"
	"os"
	"strings"
	"time"
)

const defaultUpdateFrequency = "weekly"

// Background git commands are killed after gitTimeout; a lock older than
// staleLockAge belongs to a run that did not clean up.
const (
	gitTimeout   = 2 * time.Minute
	staleLockAge = 10 * time.Minute
)

var updateFrequencies = []string{"off", "daily", "weekly", "monthly"}

func (m *manager) loadUpdateFrequency() (string, error) {
	data, err := os.ReadFile(m.settingsPath())
	if os.IsNotExist(err) {
		return defaultUpdateFrequency, nil
	}
	if err != nil {
		return "", err
	}
	frequency := defaultUpdateFrequency
	for i, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok || strings.TrimSpace(key) != "update_frequency" {
			return "", fmt.Errorf("%s:%d: invalid setting %q", m.settingsPath(), i+1, line)
		}
		frequency = strings.TrimSpace(value)
	}
	for _, allowed := range updateFrequencies {
		if frequency == allowed {
			return frequency, nil
		}
	}
	return "", fmt.Errorf("invalid update frequency %q in %s", frequency, m.settingsPath())
}

func (m *manager) saveUpdateFrequency(frequency string) error {
	for _, allowed := range updateFrequencies {
		if frequency == allowed {
			return atomicWrite(m.settingsPath(), "# Generated by omd\nupdate_frequency="+frequency+"\n")
		}
	}
	return fmt.Errorf("invalid update frequency %q", frequency)
}

func updateInterval(frequency string) (time.Duration, error) {
	switch frequency {
	case "off":
		return 0, nil
	case "daily":
		return 24 * time.Hour, nil
	case "weekly":
		return 7 * 24 * time.Hour, nil
	case "monthly":
		return 30 * 24 * time.Hour, nil
	default:
		return 0, fmt.Errorf("invalid update frequency %q", frequency)
	}
}

func (m *manager) autoUpdate() error {
	if _, err := os.Stat(m.configPath()); os.IsNotExist(err) {
		return nil
	} else if err != nil {
		return err
	}
	frequency, err := m.loadUpdateFrequency()
	if err != nil {
		return err
	}
	interval, err := updateInterval(frequency)
	if err != nil || interval == 0 {
		return err
	}
	statePath := m.settingsPath() + ".last-check"
	if data, err := os.ReadFile(statePath); err == nil {
		lastCheck, parseErr := time.Parse(time.RFC3339, strings.TrimSpace(string(data)))
		if parseErr == nil && time.Since(lastCheck) < interval {
			return nil
		}
	} else if !os.IsNotExist(err) {
		return err
	}

	lockPath := m.settingsPath() + ".update-lock"
	if err := os.Mkdir(lockPath, 0700); err != nil {
		if !os.IsExist(err) {
			return err
		}
		// A killed run leaves its lock behind; reclaim it once it outlives
		// the git timeout so background updates do not stop for good.
		info, statErr := os.Stat(lockPath)
		if statErr != nil || time.Since(info.ModTime()) < staleLockAge {
			return nil
		}
		if err := os.Remove(lockPath); err != nil {
			return err
		}
		if err := os.Mkdir(lockPath, 0700); err != nil {
			if os.IsExist(err) {
				return nil
			}
			return err
		}
	}
	defer os.Remove(lockPath)

	// Recheck under the lock so concurrent shells do not fetch repeatedly.
	if data, err := os.ReadFile(statePath); err == nil {
		lastCheck, parseErr := time.Parse(time.RFC3339, strings.TrimSpace(string(data)))
		if parseErr == nil && time.Since(lastCheck) < interval {
			return nil
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	if err := atomicWrite(statePath, time.Now().UTC().Format(time.RFC3339)+"\n"); err != nil {
		return err
	}
	return m.updateWithOptions(false, true)
}
